--------------------------------------------------------
--  Fichier créé - mardi-mars-01-2022   
--------------------------------------------------------

--------------------------------------------------------
--  DDL for Table HANDICAPE
--------------------------------------------------------

  CREATE TABLE "HANDICAPE" 
   (	"ID" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"AGE" NUMBER, 
	"TEL" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into HANDICAPE
SET DEFINE OFF;
Insert into HANDICAPE (ID,NOM,PRENOM,AGE,TEL) values ('1','p','p','1','1');
Insert into HANDICAPE (ID,NOM,PRENOM,AGE,TEL) values ('8','p','p','8','8');
Insert into HANDICAPE (ID,NOM,PRENOM,AGE,TEL) values ('7','o','o','7','7');
--------------------------------------------------------
--  DDL for Index PK_HANDICAPE
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_HANDICAPE" ON "HANDICAPE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table HANDICAPE
--------------------------------------------------------

  ALTER TABLE "HANDICAPE" ADD CONSTRAINT "PK_HANDICAPE" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HANDICAPE" MODIFY ("TEL" NOT NULL ENABLE);
  ALTER TABLE "HANDICAPE" MODIFY ("AGE" NOT NULL ENABLE);
  ALTER TABLE "HANDICAPE" MODIFY ("PRENOM" NOT NULL ENABLE);
  ALTER TABLE "HANDICAPE" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "HANDICAPE" MODIFY ("ID" NOT NULL ENABLE);
